dist: xenial
sudo: required

language: go
go_import_path: github.com/src-d/engine
go:
  - 1.11.x

matrix:
  fast_finish: true

services:
  - docker

install:
  - make bblfsh-client

script:
  - make test-coverage

before_deploy:
  - make packages

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN 
  file_glob: true
  file: build/*.tar.gz
  skip_cleanup: true
  on:
    tags: true

after_deploy:
  - DOCKER_PUSH_LATEST=1 make docker-push
